# Sudo is required to run Docker
sudo: required

# Let Travis know this is a Java project.
# Travis will run the maven commands to retrieve dependencies and build your artefact.
language: java

# Build with Open JDK 8 to ensure consistency with Docker image
jdk:
  - openjdk8

# We need Docker to build our Docker image
services:
    - docker

# Set up a cache for Maven dependencies.
# Should speed up builds.
cache:
  directories:
    - $HOME/.m2/repository

before_install:
  # Copy over our settings.xml so the build can resolve dependencies
  - cp mvn.settings.xml $HOME/.m2/settings.xml && ls $HOME/.m2/settings.xml

script:
  # Use verify to do the build so integration tests are run too
  - mvn clean verify -B -U

deploy:
  # Deploy artefact to repository if on master branch
  - provider:     script
    script:       mvn deploy -B -Dmaven.test.skip
    skip_cleanup: true
    on:
      branch:     master

